server:
  port: 8888
spring:
  application:
    name: 'main-service'
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: manager
    password: manager
  jpa:
    show-sql: true

customer:
  backendServiceHost: localhost
  backendServicePort: 8080
